[config]
# Generate colors for Sway
[[config.post_process]]
command = "swaymsg reload"
only_on_change = true

[[config.post_process]]
command = "bash ~/.config/sway/script/update-icons.sh '{{colors.primary.default.hex}}'"
only_on_change = true

[[config.templates.sway]]
input_path = "~/.config/matugen/templates/sway-colors.tpl"
output_path = "~/.config/sway/config.d/colors"

[[config.templates.css]]
input_path = "~/.config/matugen/templates/colors.tpl"
output_path = "~/.config/matugen/colors.css"

[[config.templates.fuzzel]]
input_path = "~/.config/matugen/templates/fuzzel.tpl"
output_path = "~/.config/fuzzel/fuzzel.ini"
