--ozone-platform-hint=auto
--ozone-platform=wayland
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebUIDarkMode,WebRTCPipeWireCapturer,VaapiVideoDecoder,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL
--enable-gpu
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
--force-dark-mode
