[preferred]
# Use wlr for screen sharing and screenshots
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr

# Use xapp for settings (needed for that dark mode/theme sync)
org.freedesktop.impl.portal.Settings=xapp;gtk

# Use gtk for everything else (file picker, app chooser, etc)
default=gtk
